### ISSUE TITLE
Understand and fix the Error in extendscript toolkit execution 

### ISSUE THREAD

**Issue by vogelino** [vogelino/es2015-2-extendScript-build#15]
The following line is marked as red and no information is shown in the console when executing the generated output:

``
$entries   = DEFAULT ? !DEF_VALUES ? $default : getMethod('entries') : undefined
``

![bildschirmfoto 2016-04-27 um 20 59 40](https://cloud.githubusercontent.com/assets/2759340/14868090/19215816-0ccc-11e6-8ac9-1553e818e2ca.png)

I am doing something wrong but I don't know what yet. Configuring babelify with browserify is a real headache! :(

**Comment by vogelino** [comment]
After some tests, I was able to figure out that the problem was the nested ternary operators. After correcting manually the polyfill to test it out, all ternary errors disappear and a popup appears showing the following error:

<img width="737" alt="bildschirmfoto 2016-04-27 um 22 57 27" src="https://cloud.githubusercontent.com/assets/2759340/14868070/eea8739e-0ccb-11e6-9131-6946aaa9b05b.png">

As I have no clue about what this error means, I am a bit lost. @fabiantheblind: Any idea?

**Comment by fabiantheblind** [comment]
Maybe. But my day is full today. I can run some tests tomorrow

**Comment by fabiantheblind** [comment]
Can I clone the repo to test and reproduce the error? I think it is something trivial. 

Try to run the script not from estk. Put it into iIDs scripts panel folder and run it directly. Just to see what's going on.

**Comment by fabiantheblind** [comment]
Ah oh. We can't use things where $ is used. 
This is already taken in extendscript. 
I had no problems using the es5shim library.

**Comment by fabiantheblind** [comment]
https://github.com/es-shims/es5-shim

I included the es5shim and the es5sham and the polyfill for the object define property thingy

**Comment by vogelino** [comment]
es5-shim shouldn't be needed as we already use babel polyfill. Anyway, I got the reason why the popup is showing up: we should execute the script via the scripts panel within Illustrator. There, another error is showing up: the Object.defineProperty error you meant in #18 
It turns this issue into deprecated/duplicate. I close it now
