### ISSUE TITLE
error running gulp

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/es2015-2-extendScript-build#16]

**Comment by fabiantheblind** [comment]
I get the following error:  

[07:59:17] Using gulpfile /Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build/gulpfile.js
[07:59:17] Starting 'es2015-to-es5'...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build/babel-polyfill' from '/Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build'
    at /Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build/node_modules/resolve/lib/async.js:55:21
    at load (/Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build/node_modules/resolve/lib/async.js:69:43)
    at onex (/Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build/node_modules/resolve/lib/async.js:92:31)
    at /Applications/Adobe InDesign CC 2015/Scripts/Scripts Panel/es2015-2-extendScript-build/node_modules/resolve/lib/async.js:22:47

**Comment by fabiantheblind** [comment]
What is "babel-polyfill"?

**Comment by vogelino** [comment]
> This will emulate a full ES2015 environment and is intended to be used in an application rather than a library/tool. This polyfill is automatically loaded when using babel-node.

> This means you can use new built-ins like Promise or WeakMap, static methods like Array.from or Object.assign, instance methods like Array.includes, and generator functions (provided you use the regenerator plugin). The polyfill adds to the global scope as well as native prototypes like String in order to do this.


http://babeljs.io/docs/usage/polyfill/

**Comment by fabiantheblind** [comment]
hm. it is in the package.json Why can't he find it…

**Comment by vogelino** [comment]
Weird, it worked last night! D**mn

**Comment by fabiantheblind** [comment]
do you have something globally installed?

**Comment by vogelino** [comment]
something? Whar do you mean something?

**Comment by vogelino** [comment]
I have lots of stuff installed globally but I made sure that all dependencies for the project were installed locally

**Comment by fabiantheblind** [comment]
well maybe some module that is globally installed that I don't have

**Comment by vogelino** [comment]
Now with it deprecated as I do it via NPM with a custom babel-polyfill
