### ISSUE TITLE
Could we get rid of gulp? (and other dependencies)

### ISSUE THREAD

**Issue by fabiantheblind** [vogelino/es2015-2-extendScript-build#17]
I would love if the dependencies would be as low as possible.  
browserify, babelify, gulp, all that. Creates new problems. Where possible we should use code we've written ourselves. e.g.

**Comment by vogelino** [comment]
CAN I KICK IT (GULP)? 👏   YES YOU CAN! 👏


But no stress… Let's achieve to compile es2015 to a working ExtedScript env first. I still didn't achieve to make the babel-polyfill working.

**Comment by fabiantheblind** [comment]
Yeah right. First it needs to run. Then we can refactor

**Comment by fabiantheblind** [comment]
awesome. Way better.
